<template>
  <div v-highlight>
    <md1-md></md1-md>
  </div>
  <div class="tree-view-box">
    <m-tree :options="treeOptions"></m-tree>
  </div>
  <div v-highlight>
    <md2-md></md2-md>
  </div>
  <div class="tree-view-box">
    <m-tree :options="treeOptions1" :defaultOpenNodes="['0-2','2-2']"></m-tree>
  </div>
  <div v-highlight>
    <md3-md></md3-md>
  </div>
  <div class="tree-view-box">
    <m-tree :options="treeOptions2" multiple :defaultOpenNodes="['0']"></m-tree>
  </div>
  <div v-highlight>
    <md4-md></md4-md>
  </div>
  <div class="tree-view-box">
    <m-tree :options="treeOptions3" multiple :defaultSelectNodes="['0-1','0-2-1-0']"></m-tree>
  </div>
  <div v-highlight>
    <md5-md></md5-md>
  </div>
  <div class="tree-view-box">
    <m-tree :options="treeOptions4" :defaultOpenNodes="['0-2']"></m-tree>
  </div>
  <div v-highlight>
    <md6-md></md6-md>
  </div>
  匹配不同格式正在完善...
  <div v-highlight>
    <md7-md></md7-md>
  </div>
  
  <m-table :options="options1"></m-table>
  <br/>
  <p class="titlep">options 配置项</p>
  <m-table :options="options3"></m-table>
  <br/>
  <p class="titlep">Events</p>
  <span class="titlespan">事件列表</span>
  <m-table :options="options2"></m-table>
  <div style="margin-bottom:30px"></div>
</template>

<script setup>
  import { reactive } from 'vue';
  import { VueComponent as md1Md } from '@/page/md/tree/md1.md';
  import { VueComponent as md2Md } from '@/page/md/tree/md2.md';
  import { VueComponent as md3Md } from '@/page/md/tree/md3.md';
  import { VueComponent as md4Md } from '@/page/md/tree/md4.md';
  import { VueComponent as md5Md } from '@/page/md/tree/md5.md';
  import { VueComponent as md6Md } from '@/page/md/tree/md6.md';
  import { VueComponent as md7Md } from '@/page/md/tree/md7.md';
  const state = reactive({
    treeOptions:[
      {
        label:"一级",
        value:"",
        children:[
          {
            label:"一级1",
            value:"",
          },
          {
            label:"一级2",
            value:"",
          },
          {
            label:"一级3",
            value:"",
            children:[
              {
                label:"一级3-1",
                value:"",
              },
              {
                label:"一级3-2",
                value:"",
                children:[
                  {
                    label:"一级3-2-1",
                    value:"",
                  },
                  {
                    label:"一级3-2-2",
                    value:"",
                  },
                  {
                    label:"一级3-2-3",
                    value:"",
                  }
                ]
              },
              {
                label:"一级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"二级",
        value:"",
        children:[
          {
            label:"二级1",
            value:"",
          },
          {
            label:"二级2",
            value:"",
          },
          {
            label:"二级3",
            value:"",
            children:[
              {
                label:"二级3-1",
                value:"",
                children:[
                  {
                    label:"二级3-1-1",
                    value:"",
                  },
                  {
                    label:"二级3-1-2",
                    value:"",
                  },
                  {
                    label:"二级3-1-3",
                    value:"",
                  }
                ]
              },
              {
                label:"二级3-2",
                value:"",
              },
              {
                label:"二级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"三级",
        value:"",
        children:[
          {
            label:"三级1",
            value:"",
          },
          {
            label:"三级2",
            value:"",
          },
          {
            label:"三级3",
            value:"",
            children:[
              {
                label:"三级3-1",
                value:"",
              },
              {
                label:"三级3-2",
                value:"",
              },
              {
                label:"三级3-3",
                value:"",
              }
            ]
          }
        ]
      }
    ],
    treeOptions1:[
      {
        label:"一级",
        value:"",
        children:[
          {
            label:"一级1",
            value:"",
          },
          {
            label:"一级2",
            value:"",
          },
          {
            label:"一级3",
            value:"",
            children:[
              {
                label:"一级3-1",
                value:"",
              },
              {
                label:"一级3-2",
                value:"",
                children:[
                  {
                    label:"一级3-2-1",
                    value:"",
                  },
                  {
                    label:"一级3-2-2",
                    value:"",
                  },
                  {
                    label:"一级3-2-3",
                    value:"",
                  }
                ]
              },
              {
                label:"一级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"二级",
        value:"",
        children:[
          {
            label:"二级1",
            value:"",
          },
          {
            label:"二级2",
            value:"",
          },
          {
            label:"二级3",
            value:"",
            children:[
              {
                label:"二级3-1",
                value:"",
                children:[
                  {
                    label:"二级3-1-1",
                    value:"",
                  },
                  {
                    label:"二级3-1-2",
                    value:"",
                  },
                  {
                    label:"二级3-1-3",
                    value:"",
                  }
                ]
              },
              {
                label:"二级3-2",
                value:"",
              },
              {
                label:"二级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"三级",
        value:"",
        children:[
          {
            label:"三级1",
            value:"",
          },
          {
            label:"三级2",
            value:"",
          },
          {
            label:"三级3",
            value:"",
            children:[
              {
                label:"三级3-1",
                value:"",
              },
              {
                label:"三级3-2",
                value:"",
              },
              {
                label:"三级3-3",
                value:"",
              }
            ]
          }
        ]
      }
    ],
    treeOptions2:[
      {
        label:"一级",
        value:"",
        children:[
          {
            label:"一级1",
            value:"",
          },
          {
            label:"一级2",
            value:"",
          },
          {
            label:"一级3",
            value:"",
            children:[
              {
                label:"一级3-1",
                value:"",
              },
              {
                label:"一级3-2",
                value:"",
                children:[
                  {
                    label:"一级3-2-1",
                    value:"",
                  },
                  {
                    label:"一级3-2-2",
                    value:"",
                  },
                  {
                    label:"一级3-2-3",
                    value:"",
                  }
                ]
              },
              {
                label:"一级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"二级",
        value:"",
        children:[
          {
            label:"二级1",
            value:"",
          },
          {
            label:"二级2",
            value:"",
          },
          {
            label:"二级3",
            value:"",
            children:[
              {
                label:"二级3-1",
                value:"",
                children:[
                  {
                    label:"二级3-1-1",
                    value:"",
                  },
                  {
                    label:"二级3-1-2",
                    value:"",
                  },
                  {
                    label:"二级3-1-3",
                    value:"",
                  }
                ]
              },
              {
                label:"二级3-2",
                value:"",
              },
              {
                label:"二级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"三级",
        value:"",
        children:[
          {
            label:"三级1",
            value:"",
          },
          {
            label:"三级2",
            value:"",
          },
          {
            label:"三级3",
            value:"",
            children:[
              {
                label:"三级3-1",
                value:"",
              },
              {
                label:"三级3-2",
                value:"",
              },
              {
                label:"三级3-3",
                value:"",
              }
            ]
          }
        ]
      }
    ],
    treeOptions3:[
      {
        label:"一级",
        value:"",
        children:[
          {
            label:"一级1",
            value:"",
          },
          {
            label:"一级2",
            value:"",
          },
          {
            label:"一级3",
            value:"",
            children:[
              {
                label:"一级3-1",
                value:"",
              },
              {
                label:"一级3-2",
                value:"",
                children:[
                  {
                    label:"一级3-2-1",
                    value:"",
                  },
                  {
                    label:"一级3-2-2",
                    value:"",
                  },
                  {
                    label:"一级3-2-3",
                    value:"",
                  }
                ]
              },
              {
                label:"一级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"二级",
        value:"",
        children:[
          {
            label:"二级1",
            value:"",
          },
          {
            label:"二级2",
            value:"",
          },
          {
            label:"二级3",
            value:"",
            children:[
              {
                label:"二级3-1",
                value:"",
                children:[
                  {
                    label:"二级3-1-1",
                    value:"",
                  },
                  {
                    label:"二级3-1-2",
                    value:"",
                  },
                  {
                    label:"二级3-1-3",
                    value:"",
                  }
                ]
              },
              {
                label:"二级3-2",
                value:"",
              },
              {
                label:"二级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"三级",
        value:"",
        children:[
          {
            label:"三级1",
            value:"",
          },
          {
            label:"三级2",
            value:"",
          },
          {
            label:"三级3",
            value:"",
            children:[
              {
                label:"三级3-1",
                value:"",
              },
              {
                label:"三级3-2",
                value:"",
              },
              {
                label:"三级3-3",
                value:"",
              }
            ]
          }
        ]
      }
    ],
    treeOptions4:[
      {
        label:"一级",
        value:"",
        children:[
          {
            label:"一级1",
            value:"",
          },
          {
            label:"一级2",
            value:"",
            disabled:true,
          },
          {
            label:"一级3",
            value:"",
            children:[
              {
                label:"一级3-1",
                value:"",
              },
              {
                label:"一级3-2",
                value:"",
                disabled:true,
                children:[
                  {
                    label:"一级3-2-1",
                    value:"",
                  },
                  {
                    label:"一级3-2-2",
                    value:"",
                  },
                  {
                    label:"一级3-2-3",
                    value:"",
                  }
                ]
              },
              {
                label:"一级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"二级",
        value:"",
        children:[
          {
            label:"二级1",
            value:"",
          },
          {
            label:"二级2",
            value:"",
          },
          {
            label:"二级3",
            value:"",
            children:[
              {
                label:"二级3-1",
                value:"",
                children:[
                  {
                    label:"二级3-1-1",
                    value:"",
                  },
                  {
                    label:"二级3-1-2",
                    value:"",
                  },
                  {
                    label:"二级3-1-3",
                    value:"",
                  }
                ]
              },
              {
                label:"二级3-2",
                value:"",
              },
              {
                label:"二级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"三级",
        value:"",
        children:[
          {
            label:"三级1",
            value:"",
          },
          {
            label:"三级2",
            value:"",
          },
          {
            label:"三级3",
            value:"",
            children:[
              {
                label:"三级3-1",
                value:"",
              },
              {
                label:"三级3-2",
                value:"",
              },
              {
                label:"三级3-3",
                value:"",
              }
            ]
          }
        ]
      }
    ],
    treeOptions5:[
      {
        label:"一级",
        value:"",
        children:[
          {
            label:"一级1",
            value:"",
          },
          {
            label:"一级2",
            value:"",
          },
          {
            label:"一级3",
            value:"",
            children:[
              {
                label:"一级3-1",
                value:"",
              },
              {
                label:"一级3-2",
                value:"",
                children:[
                  {
                    label:"一级3-2-1",
                    value:"",
                  },
                  {
                    label:"一级3-2-2",
                    value:"",
                  },
                  {
                    label:"一级3-2-3",
                    value:"",
                  }
                ]
              },
              {
                label:"一级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"二级",
        value:"",
        children:[
          {
            label:"二级1",
            value:"",
          },
          {
            label:"二级2",
            value:"",
          },
          {
            label:"二级3",
            value:"",
            children:[
              {
                label:"二级3-1",
                value:"",
                children:[
                  {
                    label:"二级3-1-1",
                    value:"",
                  },
                  {
                    label:"二级3-1-2",
                    value:"",
                  },
                  {
                    label:"二级3-1-3",
                    value:"",
                  }
                ]
              },
              {
                label:"二级3-2",
                value:"",
              },
              {
                label:"二级3-3",
                value:"",
              }
            ]
          }
        ]
      },
      {
        label:"三级",
        value:"",
        children:[
          {
            label:"三级1",
            value:"",
          },
          {
            label:"三级2",
            value:"",
          },
          {
            label:"三级3",
            value:"",
            children:[
              {
                label:"三级3-1",
                value:"",
              },
              {
                label:"三级3-2",
                value:"",
              },
              {
                label:"三级3-3",
                value:"",
              }
            ]
          }
        ]
      }
    ],
    options1:{
      fileds:[
        {field:'attr',title:'参数',align:'center'},
        {field:'type',title:'类型',align:'center'},
        {field:'red',title:'说明',align:'center',width:'350px'},
        {field:'sel',title:'可选值',align:'center',width:'350px'},
        {field:'def',title:'默认值',align:'center'}
      ],
      datas:[
        {attr:'options',type:'Array',red:'绑定树形组件的数据,具体见下方 options 配置',sel:'——',def:"——"},
        {attr:'multiple',type:'Boolean',red:'是否可选择',sel:'true / false',def:"false"},
        {attr:'defaultOpenNodes',type:'Array',red:'默认展开节点key',sel:'——',def:"[]"},
        {attr:'defaultSelectNodes',type:'Array',red:'默认选中节点key',sel:'——',def:"[]"},
        {attr:'customClass',type:'String',red:'自定义组件类名',sel:'——',def:"——"}
      ]
    },
    options2:{
      fileds:[
        {field:'name',title:'事件名',align:'center'},
        {field:'red',title:'说明',align:'center',width:'350px'},
        {field:'attr',title:'回调参数',align:'center'},
        {field:'exm',title:'示例',align:'center',width:'350px'}
      ],
      datas:[
        {name:"nodeClick",red:'节点点击或选中时的数据',attr:'(value:object|array)',exm:'nodeClick = (item) =>{console.log(item)}'}
      ]
    },
    options3:{
      fileds:[
        {field:'attr',title:'参数',align:'center'},
        {field:'type',title:'类型',align:'center'},
        {field:'red',title:'说明',align:'center',width:'350px'},
        {field:'sel',title:'可选值',align:'center',width:'350px'},
        {field:'def',title:'默认值',align:'center'}
      ],
      datas:[
        {attr:'label',type:'String',red:'默认文本展示字段，可设置 labelFiled 进行替换',sel:'——',def:"lable"},
        {attr:'children',type:'Array',red:'节点子集数据',sel:'——',def:"——"},
        {attr:'disabled',type:'Boolean',red:'是否禁用',sel:'true / false',def:"——"},
        {attr:'*',type:'String',red:'其他自定拓展配置字段，如：id、vlaue',sel:'——',def:"——"},
      ]
    },
  })
  const {options1,options2,treeOptions,treeOptions1,treeOptions2,treeOptions3,treeOptions4,treeOptions5,options3} = state
</script>

<style lang="scss" scoped>
  .tree-view-box{
    padding:10px;
    border:1px solid #f0f0f0;
    border-radius: 5px;
  }
</style>
